name: User CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci_cd_common:
    uses: raghudevopsb87/reusable-github-actions/.github/workflows/ci.yml@main
    with:
      component: user
      apptype: nodejs

